# Generated by Django 4.0.4 on 2022-05-02 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_addr',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
