# Generated by Django 4.0.3 on 2022-05-14 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_interact', 'Can the user interact')]},
        ),
    ]
