# Generated by Django 4.0.4 on 2022-04-25 14:27

from django.db import migrations, models
import user_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageFile',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.BinaryField(default=user_management.models.get_def_avatar),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_addr',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
