# Generated by Django 4.0.3 on 2022-05-11 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_profile_email_addr_remove_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('can_interact', 'Can the user interact')]},
        ),
    ]
