# Generated by Django 4.0.3 on 2022-05-14 23:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import item_catalog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_management', '0002_alter_profile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('project_type', models.CharField(max_length=40)),
                ('field', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('image', models.BinaryField(default=item_catalog.models.get_def_proj_avatar)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=item_catalog.models.one_week_hence, validators=[item_catalog.models.due_date_validation])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
            options={
                'permissions': [('administrate_projects', 'Can administrate project')],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[item_catalog.models.empty_string_validation])),
                ('flagged', models.BooleanField(default=False)),
                ('likes', models.ManyToManyField(blank=True, default=[0], related_name='post_like', to='user_management.profile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_catalog.project')),
                ('ratings', models.ManyToManyField(blank=True, default=[0], related_name='post_rating', to='item_catalog.rating')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('body', models.TextField(max_length=500, validators=[item_catalog.models.empty_string_validation])),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item_catalog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
        ),
    ]
