# Generated by Django 4.0.4 on 2022-04-28 20:12

from django.db import migrations, models
import django.db.models.deletion
import item_catalog.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='')),
                ('image_data', models.BinaryField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('type', models.CharField(max_length=40)),
                ('field', models.CharField(max_length=50)),
                ('keywords', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('status', models.CharField(max_length=20)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('due_date', models.DateField(default=item_catalog.models.one_week_hence, validators=[item_catalog.models.due_date_validation])),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_catalog.imagefile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item_catalog.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, validators=[item_catalog.models.empty_string_validation])),
                ('flagged', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_catalog.project')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('body', models.TextField(max_length=500, validators=[item_catalog.models.empty_string_validation])),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_catalog.comment')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='item_catalog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_catalog.profile')),
            ],
        ),
    ]
