# Generated by Django 4.0.4 on 2022-05-08 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type',
            new_name='project_type',
        ),
    ]
