# Generated by Django 4.0.4 on 2022-05-08 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_profile_email_addr_remove_profile_name'),
        ('item_catalog', '0002_rename_type_project_project_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile'),
        ),
    ]
