# Generated by Django 4.0.4 on 2022-05-06 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0002_remove_post_flagged_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
    ]
