# Generated by Django 4.0.3 on 2022-05-09 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0003_remove_comment_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('administrate_projects', 'Can administrate project')]},
        ),
    ]
