# Generated by Django 4.0.4 on 2022-05-08 20:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_profile_email_addr_remove_profile_name'),
        ('item_catalog', '0003_alter_project_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_value', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_management.profile')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='item_catalog.rating'),
        ),
    ]
