# Generated by Django 4.0.4 on 2022-05-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0004_rating_post_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rating',
        ),
        migrations.AddField(
            model_name='post',
            name='ratings',
            field=models.ManyToManyField(related_name='post_rating', to='item_catalog.rating'),
        ),
    ]
