# Generated by Django 4.0.4 on 2022-05-08 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0005_remove_post_rating_post_ratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='ratings',
        ),
    ]
