# Generated by Django 4.0.4 on 2022-05-08 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_catalog', '0006_remove_post_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ratings',
            field=models.ManyToManyField(default=0, related_name='post_rating', to='item_catalog.rating'),
        ),
    ]
