# Generated by Django 4.0.3 on 2022-05-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_remove_profile_email_addr_remove_profile_name'),
        ('item_catalog', '0009_alter_post_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, default=[0], related_name='post_like', to='user_management.profile'),
        ),
    ]
